[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx/supervisor.out.log
stderr_logfile=/var/log/nginx/supervisor.err.log

[program:backend]
command=uvicorn app.main:app --host 127.0.0.1 --port 8000
autostart=true
autorestart=true
stdout_logfile=/var/log/backend.out.log
stderr_logfile=/var/log/backend.err.log
